; функции включаются или выключаются установкой значений yes или no

[other]
; воспроизвести звуковой сигнал при загрузке
beep = yes
; восстановление функции телепорта на клавишу ENTER в режиме полёта (demo_record 1)
teleport = yes

; =======================================================

; восстановление удалённых консольных команд
[restore_deleted_commands]
; восстановить команды g_god и g_unlimitedammo
cheats	=	yes
; восстановить команды fov и hud_fov (не актуально для Enhanced Edition, т.к. там есть аналоги)
fov		=	yes

; =======================================================

; раскачка оружия
; настройки из какого-то мода раскачки для шестого патча
[wpn_bobbing_effector]
enabled					=	yes
run_amplitude			=	0.0045
walk_amplitude			=	0.0035
limp_amplitude			=	0.0025
run_speed				=	8.0
walk_speed				=   6.0
limp_speed				=	5.0

; настройки из OGSR Engine
;[wpn_bobbing_effector]
;enabled				=	yes
;run_amplitude			=	0.0075
;walk_amplitude			=	0.005
;limp_amplitude			=	0.011
;run_speed				=	6.74
;walk_speed				=   6.26
;limp_speed				=	4.6
